  name: server-deploy

  on:
    push:
      branches:
        - main
        - develop
        - cicd/deploy
    workflow_dispatch:


  env:
    PROJECT_ID: ${{ secrets.GCE_PROJECT }}

  jobs:
    server-deploy:
      permissions:
        contents: read
        id-token: write
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Authorize
          uses: 'google-github-actions/auth@v0'
          with:
            workload_identity_provider: 'projects/315948348563/locations/global/workloadIdentityPools/workload-detector'
            service_account: 'cd-deploy@comment-detector-400115.iam.gserviceaccount.com'

        - name: Compute SSH
          id: compute-ssh
          uses: 'google-github-actions/ssh-compute@v0'
          with:
            instance_name: testing-for-deploy
            zone: asia-east1-b
            ssh_private_key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
            command: 'echo Hello world'

        - name: Test
          run: |-
            echo '${{ steps.compute-ssh.outputs.stdout }}'
            echo '${{ steps.compute-ssh.outputs.stderr }}'

